### ISSUE TITLE
undefined method `launchd_service_path'

### ISSUE THREAD

**Issue by zfhxi** [FelixKratz/SketchyBar#303]
Hello, I have typed `brew upgrade sketchybar` to upgrade sketchybar to v2.12.0. However, when I run `brew services start sketchybar`, I met some errors as follows:
```
Error: undefined method `launchd_service_path' for #<Formulary::FormulaNamespace11e58b0da59c2fdb147aa27048e95331::Sketchybar:0x0000000127984ce8>
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58:in `service_file'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:94:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:86:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:86:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:112:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

My mac has been upgraded to macOS Ventura 13.1 and the version of xcode is 14.1.
Can anyone help me?

**Comment by bashu** [comment]
offtopic, but both yabai and sketchybar available via MacPorts

**Comment by zfhxi** [comment]
you are right, it works after `brew update && brew upgrade && brew cleanup`.
